[package]
name = "khdl_std"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[build-dependencies]
khdl_util.workspace = true

itertools.workspace = true
