[package]
name = "lsp_server"
version.workspace = true
edition.workspace = true

[dependencies]
language.workspace = true

log.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower-lsp.workspace = true