[package]
name = "hwlang"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = { version = "0.20.2", path="../lalrpop/lalrpop" }

[dependencies]
lalrpop-util = { version = "0.20.2", features = ["lexer", "unicode"], path="../lalrpop/lalrpop-util" }
