[package]
name = "hwlang"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = { version = "0.20.2" }

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
lalrpop-util = { version = "0.20.2", features = ["lexer", "unicode"] }
