[package]
name = "hwl_python"
edition.workspace = true
version.workspace = true

[lib]
name = "hwl"
crate-type = ["cdylib"]

[dependencies]
hwl_language.workspace = true

# TODO specify ABI?
pyo3 = { version = "0.24.0", features = ["extension-module"] }
