[package]
name = "hwl_python"
edition.workspace = true
version.workspace = true

[lib]
name = "hwl"
crate-type = ["cdylib"]

[dependencies]
hwl_language.workspace = true

itertools.workspace = true
num-bigint.workspace = true
pyo3.workspace = true
