from os import PathLike
from typing import Any, Iterator, Literal

Path = str | PathLike[str]


def format_file(source: str) -> str: ...


class Source:
    def __init__(self) -> None: ...

    @property
    def files(self) -> list[str]: ...

    @staticmethod
    def new_from_manifest_path(manifest_path: str) -> "Source": ...

    def add_file_content(self, steps: list[str], debug_info_path: str, content: str) -> None: ...

    def add_tree(self, steps: list[str], path: str) -> None: ...

    def parse(self) -> "Parsed": ...

    def compile(self) -> "Compile": ...


class Parsed:
    @property
    def source(self) -> Source: ...

    def compile(self) -> "Compile": ...


class Compile:
    @property
    def parsed(self) -> Parsed: ...

    def resolve(self, path: str) -> Any: ...

    def resolve_module(self, path: str) -> "Module": ...

    def capture_prints(self, capture: "CapturePrints | None" = None) -> "CapturePrintsContext": ...


class CapturePrints:
    def __init__(self) -> None: ...

    @property
    def prints(self) -> list[str]: ...


class CapturePrintsContext:
    def __enter__(self) -> CapturePrints: ...

    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> bool: ...


class Value:
    def __repr__(self) -> str: ...

    def __eq__(self, other: Any) -> bool: ...

    def __ne__(self, other: Any) -> bool: ...

    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

    def __getattr__(self, attr: str) -> Any: ...


class Range:
    def __init__(self, start: int | None, end: int | None) -> None: ...

    @property
    def start(self) -> int | None: ...

    @property
    def end(self) -> int | None: ...

    def contains(self, value: int) -> bool: ...

    def contains_range(self, other: "Range") -> bool: ...

    def __str__(self) -> str: ...


class Module(Value):
    def as_verilog(self) -> "ModuleVerilog": ...

    def as_verilated(
            self,
            build_dir: Path,
            *,
            extra_verilog_files: list[Path] | None = None,
    ) -> "ModuleVerilated": ...

    def as_simulator(self) -> "SimulatorModule": ...


class ModuleVerilog:
    @property
    def module_name(self) -> str: ...

    @property
    def source(self) -> str: ...


class ModuleVerilated:
    def instance(self, trace_path: str | None = None) -> "VerilatedInstance": ...


class VerilatedInstance:
    @property
    def ports(self) -> "VerilatedPorts": ...

    def step(self, increment_time: int) -> None: ...

    def save_trace(self) -> None: ...


class VerilatedPorts:
    def __getattr__(self, name: str) -> "VerilatedPort": ...

    def __getitem__(self, key: str) -> "VerilatedPort": ...

    def __setattr__(self, name: str, value: Any) -> None: ...

    def __iter__(self) -> Iterator[str]: ...


class VerilatedPort:
    @property
    def value(self) -> Any: ...

    @value.setter
    def value(self, value: Any) -> None: ...

    @property
    def type(self) -> Value: ...

    @property
    def name(self) -> str: ...

    @property
    def direction(self) -> str: ...

    def __bool__(self) -> bool: ...


class SimulatorModule:
    def instance(self) -> "SimulatorInstance": ...


class SimulatorInstance:
    @property
    def ports(self) -> "SimulatorPorts": ...

    def step(self, increment_time: int) -> None: ...


class SimulatorPorts:
    def __getattr__(self, name: str) -> "SimulatorPort": ...

    def __getitem__(self, key: str) -> "SimulatorPort": ...

    def __setattr__(self, name: str, value: Any) -> None: ...

    def __iter__(self) -> Iterator[str]: ...


class SimulatorPort:
    @property
    def value(self) -> Any: ...

    @value.setter
    def value(self, value: Any) -> None: ...

    @property
    def type(self) -> Value: ...

    @property
    def name(self) -> str: ...

    @property
    def direction(self) -> str: ...

    def __bool__(self) -> bool: ...


class HwlException(Exception): ...


class DiagnosticException(HwlException):
    @property
    def diagnostics(self) -> list[Diagnostic]: ...

    @property
    def combined_string(self) -> str: ...

    @property
    def combined_string_colored(self) -> str: ...


class Diagnostic:
    @property
    def level(self) -> Literal["error", "warning"]: ...

    @property
    def title(self) -> str: ...

    @property
    def messages(self) -> list[str]: ...

    @property
    def infos(self) -> list[str]: ...

    @property
    def full_string(self) -> str: ...

    @property
    def full_string_colored(self) -> str: ...


class SourceSetException(HwlException): ...


class DiagnosticPreviouslyReportedException(HwlException): ...


class ResolveException(HwlException): ...


class GenerateVerilogException(HwlException): ...


class VerilationException(HwlException): ...


class SimulatorException(HwlException): ...


class SimulationFinishedException(HwlException): ...
