#!/usr/bin/env bash
set -ue

cd "$(dirname "$0")"/..

cd rust
cargo build --bin khdl_language --profile profiling

COMMAND="target/profiling/khdl_language ../design/project/ --skip-lower --profile"

valgrind --tool=cachegrind --cachegrind-out-file=cachegrind.out \
  --cache-sim=yes --branch-sim=yes \
  $COMMAND

valgrind --tool=callgrind --callgrind-out-file=callgrind.out \
  $COMMAND

samply record ./target/profiling/khdl_bin ../python/profile_test/ -j1
