#!/usr/bin/env bash
set -ue

# Run all tests with coverage and generate a report
# Based on:
# * https://github.com/cjermain/rust-python-coverage
# * https://github.com/taiki-e/cargo-llvm-cov

# TODO why does this keep rebuilding? do we need a separate cargo dir?
RUST_MANIFEST_PATH="$PWD/rust/Cargo.toml"

# setup environment variables
# shellcheck disable=SC1090
source <(cargo llvm-cov --manifest-path "$RUST_MANIFEST_PATH" show-env --export-prefix)
export CARGO_TARGET_DIR=$CARGO_LLVM_COV_TARGET_DIR
export CARGO_INCREMENTAL=1

# remove old coverage data
cargo llvm-cov --manifest-path "$RUST_MANIFEST_PATH" clean --workspace

# run rust tests
(
  cd rust &&
  cargo test
)

# run python tests
(
  cd python &&
  uv run maturin dev --compression-method stored -m ../rust/hwl_python/Cargo.toml &&
  uv run pytest -n auto src/hwl_sandbox || true
)

# report coverage
IGNORE_REGEX="^$PWD/rust/(hwl_lsp_server|hwl_bin|hwl_wasm)/src/"

cargo llvm-cov --manifest-path "$RUST_MANIFEST_PATH" report --html --ignore-filename-regex "$IGNORE_REGEX"
cargo llvm-cov --manifest-path "$RUST_MANIFEST_PATH" report --text --ignore-filename-regex "$IGNORE_REGEX" \
  > "$CARGO_LLVM_COV_TARGET_DIR"/llvm-cov/coverage.txt

echo "Coverage report is available at file://$CARGO_LLVM_COV_TARGET_DIR/llvm-cov/html/index.html"
