[project]
name = "khdl_sandbox"
version = "0.1.0"
requires-python = ">=3.10,<3.15"
dependencies = [
    "khdl",
    "maturin>=1.11",
    "pytest>=9.0.2",
    "pytest-xdist>=3.8.0",
    "z3-solver>=4.15.4.0",
]

[tool.uv.sources]
khdl = { path = "../rust/khdl_python/", editable = true }

[tool.pytest.ini_options]
addopts = "--tb=short --import-mode=importlib"
testpaths = ["src/khdl_sandbox/tests"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
