[package]
name = "hwl_lsp_server"
version.workspace = true
edition.workspace = true

[dependencies]
itertools.workspace=true
hwl_language.workspace = true
log.workspace = true
lsp-server.workspace = true
lsp-types.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
anyhow = "1.0.86"
